/// Hand-maintained Dart types for the Selfwell API surface.
///
/// **Source of truth**: `docs/api/openapi.yaml` (12 tag, 41 operationId).
/// In V1.4 this file will be auto-generated by `openapi-generator-cli`
/// from the OpenAPI spec (see `docs/plan/mvp-implementation-plan.md`
/// §16.2). Until then, types are hand-written to mirror the YAML 1:1
/// so the Flutter app compiles even when the generator is not run.
///
/// **DO NOT hard-code endpoint URLs**: every URL helper below comes
/// from [ApiPaths]. The provider must consume [ApiPaths] rather than
/// typing `https://example.com/api/xxx` literals (per §17 #13 strong
/// constraint).
library;

import 'package:flutter/foundation.dart';

/// API base path. The host is configured in `main.dart` via
/// `buildDio(baseUrl: ...)`; everything below lives under `/v1`.
class ApiBase {
  ApiBase._();

  /// `version` segment of every URL. Matches the backend
  /// FastAPI `prefix="/v1"` in `app/main.py`.
  static const String version = '/v1';
}

/// Single source of truth for endpoint paths (per §17 #13).
///
/// Every URL is `/${version}/${tag}/${resource}`; no host, no scheme.
@immutable
class ApiPaths {
  const ApiPaths._();

  // ---- Auth (M1) ----
  static const String authWxLogin = '${ApiBase.version}/auth/wx-login';
  static const String authPhoneLogin = '${ApiBase.version}/auth/phone-login';
  static const String authRefresh = '${ApiBase.version}/auth/refresh';
  static const String authLogout = '${ApiBase.version}/auth/logout';

  // ---- Users (M1) ----
  static const String usersMe = '${ApiBase.version}/users/me';
  static const String usersPushToken = '${ApiBase.version}/users/me/push-token';

  // ---- Diagnosis (M2) ----
  static const String diagnosis = '${ApiBase.version}/diagnosis';
  static const String diagnosisLatest = '${ApiBase.version}/diagnosis/latest';

  /// Builds the SSE stream URL with the diagnosis id injected.
  /// `GET /diagnosis/{id}/stream` — see `docs/api/sse-events.md`.
  static String diagnosisStream(String id) =>
      '${ApiBase.version}/diagnosis/$id/stream';

  static String diagnosisById(String id) =>
      '${ApiBase.version}/diagnosis/$id';

  // ---- Plans (M3) ----
  static const String plansGenerate = '${ApiBase.version}/plans/generate';
  static const String plansToday = '${ApiBase.version}/plans/today';
  static const String plansActive = '${ApiBase.version}/plans/active';
  static String plansById(String id) => '${ApiBase.version}/plans/$id';

  // ---- Checkins (M4) ----
  static const String checkins = '${ApiBase.version}/checkins';
  static const String checkinsCalendar =
      '${ApiBase.version}/checkins/calendar';
  static const String checkinsHistory = '${ApiBase.version}/checkins/history';
  static const String checkinsStats = '${ApiBase.version}/checkins/stats';

  // ---- Videos (M3) ----
  static String videoById(String id) => '${ApiBase.version}/videos/$id';
  static const String videosSearch = '${ApiBase.version}/videos/search';
  static const String videosRecommended =
      '${ApiBase.version}/videos/recommended';

  // ---- Community (M6) ----
  static const String communityPosts = '${ApiBase.version}/community/posts';
  static String communityPostById(String id) =>
      '${ApiBase.version}/community/posts/$id';

  // ---- Share (M10) ----
  static const String sharePoster = '${ApiBase.version}/share/poster';
  static String sharePosterById(String id) =>
      '${ApiBase.version}/share/poster/$id';
  static const String shareLink = '${ApiBase.version}/share/share-link';

  // ---- Notification (M9) ----
  static const String notificationsSubscribe =
      '${ApiBase.version}/notifications/subscribe';
  static const String notificationsUnsubscribe =
      '${ApiBase.version}/notifications/unsubscribe';
  static const String notificationsHistory =
      '${ApiBase.version}/notifications/history';

  // ---- Assistant (M5) ----
  static const String assistantChat = '${ApiBase.version}/assistant/chat';
  static const String assistantEntryCards =
      '${ApiBase.version}/assistant/entry-cards';
  static const String assistantActiveSession =
      '${ApiBase.version}/assistant/sessions/active';
  static String assistantSessionClose(String id) =>
      '${ApiBase.version}/assistant/sessions/$id/close';

  // ---- Feedback (M7) ----
  static const String feedback = '${ApiBase.version}/feedback';
  static String feedbackById(String id) => '${ApiBase.version}/feedback/$id';

  // ---- Butler / Recall (M8) ----
  static const String butlerRecall = '${ApiBase.version}/butler/recall';
  static const String butlerRecallHistory =
      '${ApiBase.version}/butler/recall/history';
  static String butlerRecallMessages(String id) =>
      '${ApiBase.version}/butler/recall/$id/messages';
}

// =====================================================================
// M1 · Auth + User
// =====================================================================

@immutable
class WxLoginRequest {
  const WxLoginRequest({required this.code, this.nickName, this.avatarUrl});

  final String code;
  final String? nickName;
  final String? avatarUrl;

  Map<String, dynamic> toJson() => <String, dynamic>{
        'code': code,
        if (nickName != null) 'nickName': nickName,
        if (avatarUrl != null) 'avatarUrl': avatarUrl,
      };
}

@immutable
class AuthToken {
  const AuthToken({
    required this.accessToken,
    required this.userId,
    required this.userIdPseudo,
  });

  final String accessToken;
  final String userId;
  final String userIdPseudo;

  factory AuthToken.fromJson(Map<String, dynamic> json) => AuthToken(
        accessToken: json['access_token'] as String,
        userId: json['user_id'] as String,
        userIdPseudo: json['user_id_pseudo'] as String,
      );
}

@immutable
class UserProfile {
  const UserProfile({
    required this.userId,
    required this.nickName,
    this.avatarUrl,
    this.focusParts = const <String>[],
  });

  final String userId;
  final String nickName;
  final String? avatarUrl;
  final List<String> focusParts;

  factory UserProfile.fromJson(Map<String, dynamic> json) => UserProfile(
        userId: json['user_id'] as String,
        nickName: (json['nick_name'] as String?) ?? '你',
        avatarUrl: json['avatar_url'] as String?,
        focusParts: (json['focus_parts'] as List<dynamic>?)
                ?.map((e) => e as String)
                .toList() ??
            const <String>[],
      );
}

// =====================================================================
// M2 · Diagnosis
// =====================================================================

@immutable
class CreateDiagnosisRequest {
  const CreateDiagnosisRequest({required this.photoUrls});

  final List<String> photoUrls;

  Map<String, dynamic> toJson() => <String, dynamic>{
        'photo_urls': photoUrls,
      };
}

@immutable
class DiagnosisJob {
  const DiagnosisJob({required this.id, required this.status});

  final String id;
  final String status;

  factory DiagnosisJob.fromJson(Map<String, dynamic> json) => DiagnosisJob(
        id: json['id'] as String,
        status: json['status'] as String,
      );
}

@immutable
class DiagnosisReport {
  const DiagnosisReport({
    required this.id,
    required this.improveDirections,
    required this.tags,
    this.createdAt,
  });

  final String id;
  final List<ImproveDirection> improveDirections;
  final List<String> tags;
  final String? createdAt;

  factory DiagnosisReport.fromJson(Map<String, dynamic> json) =>
      DiagnosisReport(
        id: json['id'] as String,
        improveDirections: (json['improve_directions'] as List<dynamic>? ?? [])
            .map((e) => ImproveDirection.fromJson(e as Map<String, dynamic>))
            .toList(),
        tags: (json['tags'] as List<dynamic>? ?? const <dynamic>[])
            .map((e) => e as String)
            .toList(),
        createdAt: json['created_at'] as String?,
      );
}

@immutable
class ImproveDirection {
  const ImproveDirection({
    required this.title,
    required this.summary,
    required this.severity,
    this.videoId,
  });

  final String title;
  final String summary;
  final String severity; // 轻度 / 中度
  final String? videoId;

  factory ImproveDirection.fromJson(Map<String, dynamic> json) =>
      ImproveDirection(
        title: json['title'] as String,
        summary: json['summary'] as String,
        severity: (json['severity'] as String?) ?? '轻度',
        videoId: json['video_id'] as String?,
      );
}

// =====================================================================
// M3 · Plan
// =====================================================================

@immutable
class PlanDay {
  const PlanDay({
    required this.day,
    required this.title,
    required this.minutes,
    this.videoId,
    this.completed = false,
  });

  final int day;
  final String title;
  final int minutes;
  final String? videoId;
  final bool completed;

  factory PlanDay.fromJson(Map<String, dynamic> json) => PlanDay(
        day: (json['day'] as num).toInt(),
        title: json['title'] as String,
        minutes: (json['minutes'] as num).toInt(),
        videoId: json['video_id'] as String?,
        completed: (json['completed'] as bool?) ?? false,
      );
}

@immutable
class ActivePlan {
  const ActivePlan({
    required this.id,
    required this.days,
    required this.totalDays,
    this.phaseLabel,
  });

  final String id;
  final List<PlanDay> days;
  final int totalDays;
  final String? phaseLabel;

  factory ActivePlan.fromJson(Map<String, dynamic> json) => ActivePlan(
        id: json['id'] as String,
        days: (json['days'] as List<dynamic>? ?? const <dynamic>[])
            .map((e) => PlanDay.fromJson(e as Map<String, dynamic>))
            .toList(),
        totalDays: (json['total_days'] as num?)?.toInt() ?? 21,
        phaseLabel: json['phase_label'] as String?,
      );
}

// =====================================================================
// M4 · Checkin
// =====================================================================

@immutable
class CreateCheckinRequest {
  const CreateCheckinRequest({
    required this.planId,
    required this.day,
    this.feeling = '',
  });

  final String planId;
  final int day;
  final String feeling;

  Map<String, dynamic> toJson() => <String, dynamic>{
        'plan_id': planId,
        'day': day,
        'feeling': feeling,
      };
}

@immutable
class CheckinStats {
  const CheckinStats({
    required this.streakDays,
    required this.totalDays,
    required this.fragments,
  });

  final int streakDays;
  final int totalDays;
  final int fragments;

  factory CheckinStats.fromJson(Map<String, dynamic> json) => CheckinStats(
        streakDays: (json['streak_days'] as num?)?.toInt() ?? 0,
        totalDays: (json['total_days'] as num?)?.toInt() ?? 0,
        fragments: (json['fragments'] as num?)?.toInt() ?? 0,
      );
}

// =====================================================================
// M5 · Assistant
// =====================================================================

@immutable
class AssistantMessage {
  const AssistantMessage({
    required this.role,
    required this.content,
    this.personaState = 'warm',
  });

  final String role; // user | assistant
  final String content;
  final String personaState;

  factory AssistantMessage.fromJson(Map<String, dynamic> json) =>
      AssistantMessage(
        role: json['role'] as String,
        content: json['content'] as String,
        personaState: (json['persona_state'] as String?) ?? 'warm',
      );
}

@immutable
class AssistantChatRequest {
  const AssistantChatRequest({required this.sessionId, required this.content});

  final String sessionId;
  final String content;

  Map<String, dynamic> toJson() => <String, dynamic>{
        'session_id': sessionId,
        'content': content,
      };
}

@immutable
class AssistantChatResponse {
  const AssistantChatResponse({
    required this.sessionId,
    required this.reply,
    required this.personaState,
  });

  final String sessionId;
  final String reply;
  final String personaState;

  factory AssistantChatResponse.fromJson(Map<String, dynamic> json) =>
      AssistantChatResponse(
        sessionId: json['session_id'] as String,
        reply: json['reply'] as String,
        personaState: (json['persona_state'] as String?) ?? 'warm',
      );
}

// =====================================================================
// M6 · Community
// =====================================================================

@immutable
class CommunityPost {
  const CommunityPost({
    required this.id,
    required this.nickName,
    required this.body,
    required this.createdAt,
    this.photoUrls = const <String>[],
    this.aiComment,
  });

  final String id;
  final String nickName;
  final String body;
  final String createdAt;
  final List<String> photoUrls;
  final String? aiComment;

  factory CommunityPost.fromJson(Map<String, dynamic> json) => CommunityPost(
        id: json['id'] as String,
        nickName: (json['nick_name'] as String?) ?? '匿名',
        body: json['body'] as String,
        createdAt: json['created_at'] as String,
        photoUrls: (json['photo_urls'] as List<dynamic>?)
                ?.map((e) => e as String)
                .toList() ??
            const <String>[],
        aiComment: json['ai_comment'] as String?,
      );
}

@immutable
class CreatePostRequest {
  const CreatePostRequest({required this.body, this.photoUrls = const <String>[]});

  final String body;
  final List<String> photoUrls;

  Map<String, dynamic> toJson() => <String, dynamic>{
        'body': body,
        'photo_urls': photoUrls,
      };
}

// =====================================================================
// M7 · Feedback (mood diary)
// =====================================================================

@immutable
class FeedbackEntry {
  const FeedbackEntry({
    required this.id,
    required this.body,
    required this.createdAt,
    this.aiAck,
  });

  final String id;
  final String body;
  final String createdAt;
  final String? aiAck;

  factory FeedbackEntry.fromJson(Map<String, dynamic> json) => FeedbackEntry(
        id: json['id'] as String,
        body: json['body'] as String,
        createdAt: json['created_at'] as String,
        aiAck: json['ai_ack'] as String?,
      );
}

// =====================================================================
// M8 · Recall (compare with past self)
// =====================================================================

@immutable
class RecallSnapshot {
  const RecallSnapshot({required this.id, required this.daysAgo, this.photoUrl});

  final String id;
  final int daysAgo;
  final String? photoUrl;

  factory RecallSnapshot.fromJson(Map<String, dynamic> json) => RecallSnapshot(
        id: json['id'] as String,
        daysAgo: (json['days_ago'] as num).toInt(),
        photoUrl: json['photo_url'] as String?,
      );
}

@immutable
class RecallCompare {
  const RecallCompare({
    required this.aiSummary,
    required this.before,
    required this.now,
  });

  final String aiSummary;
  final RecallSnapshot before;
  final RecallSnapshot now;

  factory RecallCompare.fromJson(Map<String, dynamic> json) => RecallCompare(
        aiSummary: json['ai_summary'] as String,
        before: RecallSnapshot.fromJson(
          (json['before'] as Map<String, dynamic>),
        ),
        now: RecallSnapshot.fromJson(
          (json['now'] as Map<String, dynamic>),
        ),
      );
}

// =====================================================================
// M10 · Share / hug card
// =====================================================================

@immutable
class HugCard {
  const HugCard({
    required this.id,
    required this.day,
    required this.imageUrl,
  });

  final String id;
  final int day; // 7 | 14 | 21
  final String imageUrl;

  factory HugCard.fromJson(Map<String, dynamic> json) => HugCard(
        id: json['id'] as String,
        day: (json['day'] as num).toInt(),
        imageUrl: json['image_url'] as String,
      );
}
